#!/bin/bash

# Dev mode - watch and rebuild
if [ "$1" == 'dev' ]
then
    echo "Starting dev mode..."
    echo "Watching ts/, style/, html/ for changes..."
    echo "Press Ctrl+C to stop."
    echo ""

    # Run initial build
    ./build

    # Use Node.js for file watching
    node -e "
const fs = require('fs');
const { spawn } = require('child_process');
const path = require('path');

const debounce = {};

function runBuild(type) {
    const key = type;
    if (debounce[key]) clearTimeout(debounce[key]);
    debounce[key] = setTimeout(() => {
        console.log('\n[\x1b[36m' + new Date().toLocaleTimeString() + '\x1b[0m] Change detected in ' + type + ', rebuilding...');
        const proc = spawn('./build', [type], { stdio: 'inherit' });
        proc.on('close', () => console.log('[\x1b[32mready\x1b[0m] Watching for changes...'));
    }, 100);
}

function watchDir(dir, type, extensions) {
    fs.watch(dir, { recursive: true }, (event, filename) => {
        if (filename && extensions.some(ext => filename.endsWith(ext))) {
            runBuild(type);
        }
    });
    console.log('Watching ' + dir + ' for ' + extensions.join(', ') + ' changes');
}

watchDir('./ts', 'script', ['.ts']);
watchDir('./style', 'css', ['.less']);
watchDir('./html', 'html', ['.html']);

console.log('\n[\x1b[32mready\x1b[0m] Watching for changes...\n');
"
    exit 0
fi

# Typescript, Javascript
if [ -z "$1" ] || [ "$1" == 'script' ]
then
   # Typescript to Javascript
   echo "Typescript compiler."
   npx tsc --version
   npx tsc -p ./ts/
   echo "Done."

   # Javascript Compiled and Minified
   echo "Closure compiler."
   npx google-closure-compiler --externs="node_modules/google-closure-compiler/contrib/externs/jquery-3.2.js" --compilation_level=ADVANCED --js="./js/**.js" --js_output_file="./compiled/compiled.js"
   echo "Done."
fi

# Less to CSS
if [ -z "$1" ] || [ "$1" == 'css' ]
then
   echo "Less compiler."
   npx lessc ./style/style.less > ./compiled/compiled.css
   echo "Done."
fi;

# HTML
if [ -z "$1" ] || [ "$1" == 'html' ]
then
    echo "HTML minifier."
    for file in `ls html`;
    do cat "html/$file" | npx html-minifier --collapse-whitespace --remove-comments --remove-optional-tags --remove-redundant-attributes --remove-script-type-attributes --remove-tag-whitespace --use-short-doctype --minify-css true --minify-js true > $file;
    done;
    echo "Done."
fi

echo -e "\nAll Done.\n"


